# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

  
language: r
cache: packages
sudo: false

r:
  - oldrel
  - release
  - devel
os:
  - linux
  - osx

compiler:
  - gcc

after_success:
- Rscript -e 'covr::codecov()'


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master