# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

  
language: r
cache: packages
sudo: false

r:
  - oldrel
  - release
  - devel
os:
  - linux
  - osx

compiler:
  - gcc

after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'pkgdown::build_site()'
