# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

  
language: r
cache: packages
sudo: false

r:
  - oldrel
  - release
  after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'install.packages("pkgdown")'
  - Rscript -e 'pkgdown::build_site()'
  deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_PAT
    keep-history: true
    local-dir: docs
    on:
      branch: master
  - devel
os:
  - linux

compiler:
  - gcc

