# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
cache: packages

jobs:
  include:
  - r: devel
  - os: osx
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: 3.4
  - r: 3.3
  - r: 3.2
    warnings_are_errors: false


env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - _R_CHECK_SYSTEM_CLOCK_=FALSE
